export const GET_SOCIAL_URL_LOGIN = "GET_SOCIAL_URL_LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_BY_SOCIAL = "LOGIN_BY_SOCIAL";
export const LOGIN_BY_EMAIL = "LOGIN_BY_EMAIL";
export const SIGNUP_BY_EMAIL = "SIGNUP_BY_EMAIL";
