# Generated by Django 3.2.15 on 2022-11-05 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embroidery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Successful Transaction', max_length=512)),
                ('content', models.TextField(blank=True, default='<div style="font-size: 14px; line-height: 20px">\n  <div>Hi {},</div>\n  <div>Thank you very much for using our {} service.</div>\n  <div>We confirm your order has been successfully confirmed at {}:</div>\n\n  <div>See your receipt at <a href="{}">link</a></div>\n</div>\n', max_length=1000000)),
                ('footer', models.TextField(blank=True, default='<div style="display: flex">\n  <img\n    style="\n      height: 110px;\n      width: 110px;\n      content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/logo.png\');\n    "\n  />\n  <div\n    style="\n      height: 110px;\n      width: 1px;\n      background-color: black;\n      margin-right: 8px;\n    "\n  ></div>\n  <div style="font-size: 14px; line-height: 20px">\n    <div style="font-size: 18px; font-weight: 700; line-height: 24px">\n      Embroidery Digitizing\n    </div>\n    <div>(+84) 44 444 3455</div>\n    <div>263 Ngo Gia Tu, Ward 2 Distric 10, Ho Chi Minh city</div>\n    <div>abcxyz@gmail.com</div>\n    <div>Turn your idea to reality</div>\n    <div\n      style="\n        display: flex;\n        width: 200px;\n        justify-content: baseline;\n        display: inline;\n      "\n    >\n      <a href="#messenger">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/messenger.png\');\n          "\n        />\n      </a>\n      <a href="#facebook">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/facebook.png\');\n          "\n        />\n      </a>\n      <a href="#instagram">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/instagram.png\');\n          "\n        />\n      </a>\n    </div>\n  </div>\n</div>\n', max_length=1000000)),
                ('has_attach_receipt', models.BooleanField(default=True, verbose_name='Has attach receipt')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='embroidery.order')),
            ],
            options={
                'verbose_name_plural': 'Send Message',
            },
        ),
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mail', models.EmailField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('token', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'E-Mailer',
            },
        ),
        migrations.CreateModel(
            name='MailerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.email')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='embroidery.customer')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.mailer'),
        ),
    ]
