# Generated by Django 3.2.15 on 2022-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='?Sent'),
        ),
    ]
