# Generated by Django 3.2.15 on 2022-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='footer',
            field=models.TextField(blank=True, default='<div style="display: flex">\n  <img\n    style="\n      height: 110px;\n      width: 110px;\n      content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/logo.png\');\n    "\n  />\n  <div\n    style="\n      height: 110px;\n      width: 1px;\n      background-color: black;\n      margin-right: 8px;\n    "\n  ></div>\n  <div style="font-size: 14px; line-height: 20px">\n    <div style="font-size: 18px; font-weight: 700; line-height: 24px">\n      Embroidery Digitizing\n    </div>\n    <div>(+84) 44 444 3455</div>\n    <div>263 Ngo Gia Tu, Ward 2 Distric 10, Ho Chi Minh city</div>\n    <div>abcxyz@gmail.com</div>\n    <div>Turn your idea to reality</div>\n    <div\n      style="\n        display: flex;\n        width: 200px;\n        justify-content: baseline;\n        display: inline;\n      "\n    >\n      <!-- <a href="#messenger">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/messenger.png\');\n          "\n        />\n      </a>\n      <a href="#facebook">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/facebook.png\');\n          "\n        />\n      </a>\n      <a href="#instagram">\n        <img\n          style="\n            height: 18px;\n            width: 18px;\n            content: url(\'http://127.0.0.1:8000/static/admin/simpleui-x/img/instagram.png\');\n          "\n        />\n      </a> -->\n    </div>\n  </div>\n</div>\n', max_length=1000000),
        ),
    ]
