# Generated by Django 3.2.15 on 2022-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_email_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailer',
            name='token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
    ]
