# Generated by Django 3.2.15 on 2022-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20221004_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Send Message'},
        ),
        migrations.AlterModelOptions(
            name='mailer',
            options={'verbose_name_plural': 'E-Mailer'},
        ),
    ]
