# Generated by Django 3.2.15 on 2022-10-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0030_auto_20221008_1435'),
        ('contact', '0004_auto_20221004_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maileremail',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='embroidery.customer'),
        ),
    ]
