# Generated by Django 3.2.15 on 2022-10-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0031_auto_20221008_1509'),
        ('contact', '0005_alter_maileremail_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='embroidery.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.mailer'),
        ),
        migrations.AlterField(
            model_name='email',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
