# Generated by Django 3.2.15 on 2022-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emboridery", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="image",
            field=models.ImageField(upload_to="static/orders/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("in_progress", "IN_PROGRESS"),
                    ("pending", "PEDNING"),
                    ("resolve", "RESOLVE"),
                    ("close", "CLOSE"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
