# Generated by Django 3.2.15 on 2022-10-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emboridery", "0004_auto_20221003_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emboridery.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="end_time",
            field=models.DateTimeField(blank=True, verbose_name="End"),
        ),
        migrations.AlterField(
            model_name="order",
            name="start_time",
            field=models.DateTimeField(blank=True, verbose_name="Start"),
        ),
    ]
