# Generated by Django 3.2.15 on 2022-10-05 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emboridery', '0008_auto_20221003_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='static/sample/')),
                ('height', models.FloatField(blank=True, default=0, verbose_name='Height')),
                ('width', models.FloatField(blank=True, default=0, verbose_name='Width')),
                ('length', models.FloatField(blank=True, default=0, verbose_name='Length')),
                ('output_format', models.CharField(choices=[('JPEG', 'JPEG'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('PDF', 'PDF'), ('DST', 'DST'), ('EMB', 'EMB'), ('PES', 'PES'), ('CND', 'CND'), ('EXP', 'EXP'), ('VP3', 'VP3'), ('JEF', 'JEF'), ('HUS', 'HUS'), ('ART', 'ART')], default='PDF', max_length=50)),
            ],
        ),
    ]
