# Generated by Django 3.2.15 on 2022-10-07 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emboridery', '0009_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name_plural': 'Sample'},
        ),
        migrations.AlterField(
            model_name='sample',
            name='output_format',
            field=models.CharField(choices=[('JPEG', 'JPEG'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('PDF', 'PDF'), ('DST', 'DST'), ('EMB', 'EMB'), ('PES', 'PES'), ('CND', 'CND'), ('EXP', 'EXP'), ('VP3', 'VP3'), ('JEF', 'JEF'), ('HUS', 'HUS'), ('ART', 'ART')], default='PNG', max_length=50),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('init', 'INIT'), ('paid', 'PAID'), ('debt', 'DEBT')], default='init', max_length=50)),
                ('payment_method', models.CharField(choices=[('momo', 'MOMO'), ('card', 'CARD'), ('transfer', 'TRANSFER'), ('manual', 'MANUAL')], default='card', max_length=50)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emboridery.order')),
            ],
            options={
                'verbose_name_plural': 'Invoice',
            },
        ),
    ]
