# Generated by Django 3.2.15 on 2022-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emboridery', '0016_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=2022, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
