# Generated by Django 3.2.15 on 2022-10-07 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emboridery', '0017_auto_20221007_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start'),
        ),
    ]
