# Generated by Django 4.1.3 on 2023-02-19 14:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountLogin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "list_account",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True, max_length=10),
                            blank=True,
                            size=10,
                        ),
                        default=list,
                        size=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistToken",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("token", models.CharField(max_length=500, unique=True)),
                ("blacklisted_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Customer 1676817823", max_length=256),
                ),
                ("email", models.EmailField(blank=True, max_length=70)),
                ("address", models.CharField(blank=True, max_length=256)),
                ("password", models.BinaryField(blank=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "INDIVIDUAL"),
                            ("organization", "ORGANIZATION"),
                        ],
                        default="individual",
                        max_length=50,
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("normal", "NORMAL"),
                            ("google", "GOOGLE"),
                            ("facebook", "FACEBOOK"),
                        ],
                        default="google",
                        max_length=50,
                    ),
                ),
                ("company", models.CharField(blank=True, default="", max_length=256)),
                ("image", models.CharField(blank=True, default="", max_length=500)),
                (
                    "code_confirm",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_confirm", models.BooleanField(default=True)),
                ("meta_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Customer",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Ref"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Order 1676817823", max_length=256, verbose_name="Tên"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Mở"),
                            ("in_progress", "Đang thực hiện"),
                            ("done", "Hoàn tất"),
                            ("cancel", "Hủy bỏ"),
                        ],
                        default="open",
                        max_length=50,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[("vector", "Vector"), ("embroidery", "Embroidery")],
                        default="vector",
                        max_length=10,
                        verbose_name="Loại đầu ra",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("transfer", "Chuyển khoản"),
                            ("manual", "Thủ công"),
                        ],
                        default="card",
                        max_length=50,
                        verbose_name="Phương thức",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("quote", "Báo giá"), ("order", "Đặt hàng")],
                        default="order",
                        max_length=5,
                        verbose_name="Loại yêu cầu",
                    ),
                ),
                (
                    "receipt_pdf",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="static/receipt/pdf/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Order",
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="static/sample/")),
                (
                    "height",
                    models.FloatField(blank=True, default=0, verbose_name="Height"),
                ),
                (
                    "width",
                    models.FloatField(blank=True, default=0, verbose_name="Width"),
                ),
                (
                    "length",
                    models.FloatField(blank=True, default=0, verbose_name="Length"),
                ),
            ],
            options={
                "verbose_name_plural": "Sample",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256)),
                ("address", models.CharField(blank=True, max_length=256)),
                ("agency", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "height",
                    models.FloatField(blank=True, default=0, verbose_name="Dài"),
                ),
                (
                    "width",
                    models.FloatField(blank=True, default=0, verbose_name="Rộng"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("inches", "inches"), ("mm", "mm")],
                        default="inches",
                        max_length=6,
                        verbose_name="Đơn vị đo",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, default=1, verbose_name="Số lượng"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="GIá trên 1 sản phẩm",
                        max_digits=10,
                        verbose_name="Đơn vị giá",
                    ),
                ),
                (
                    "messages",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hãy nhập các thông tin yêu cầu",
                        max_length=2048,
                        verbose_name="Thông tin",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sản phẩm",
            },
        ),
        migrations.CreateModel(
            name="OutputFormat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("JPEG", "JPEG"),
                            ("JPG", "JPG"),
                            ("PNG", "PNG"),
                            ("PDF", "PDF"),
                            ("XXX", "XXX"),
                            ("ART", "ART"),
                            ("CND", "CND"),
                            ("CSD", "CSD"),
                            ("DST", "DST"),
                            ("EMB", "EMB"),
                            ("EXP", "EXP"),
                            ("HUS", "HUS"),
                            ("JEF", "JEF"),
                            ("PCS", "PCS"),
                            ("PEC", "PEC"),
                            ("PES", "PES"),
                            ("SEW", "SEW"),
                            ("VP3", "VP3"),
                            ("VIP", "VIP"),
                        ],
                        default="PDF",
                        max_length=50,
                        verbose_name="Đầu ra",
                    ),
                ),
                (
                    "product_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.productrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đầu ra",
                "verbose_name_plural": "Đầu ra",
            },
        ),
        migrations.CreateModel(
            name="MessageRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(blank=True, max_length=256)),
                (
                    "product_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.productrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh sách yêu cầu",
                "verbose_name_plural": "Danh sách yêu cầu",
            },
        ),
        migrations.CreateModel(
            name="FileProductResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "efile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="static/product_response/<django.db.models.fields.related.ForeignKey>",
                        verbose_name="Hình ảnh",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh",
                "verbose_name_plural": "Hình ảnh",
            },
        ),
        migrations.CreateModel(
            name="FileProductRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="static/product_request/<django.db.models.fields.related.ForeignKey>",
                        verbose_name="Hình ảnh",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh yêu cầu",
                "verbose_name_plural": "Hình ảnh yêu cầu",
            },
        ),
    ]
