# Generated by Django 3.2.15 on 2022-11-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer 1667638811', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order 1667638811', max_length=256),
        ),
    ]
