# Generated by Django 3.2.15 on 2022-11-12 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0002_auto_20221105_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='login_type',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('google', 'GOOGLE'), ('facebook', 'FACEBOOK')], default='google', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer 1668246000', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order 1668246000', max_length=256),
        ),
    ]
