# Generated by Django 3.2.15 on 2022-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embroidery", "0003_auto_20221003_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="end_time",
            field=models.DateTimeField(auto_now=True, verbose_name="End"),
        ),
        migrations.AddField(
            model_name="order",
            name="start_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Start"),
        ),
    ]
