# Generated by Django 4.1.3 on 2023-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embroidery", "0003_alter_customer_name_alter_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(default="Customer 1676817857", max_length=256),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(
                default="Order 1676817857", max_length=256, verbose_name="Tên"
            ),
        ),
    ]
