# Generated by Django 3.2.15 on 2022-10-03 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("embroidery", "0005_auto_20221003_1343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="height",
        ),
        migrations.RemoveField(
            model_name="order",
            name="image",
        ),
        migrations.RemoveField(
            model_name="order",
            name="length",
        ),
        migrations.RemoveField(
            model_name="order",
            name="width",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("in_progress", "IN_PROGRESS"),
                    ("pending", "PEDNING"),
                    ("resolve", "RESOLVE"),
                    ("finish", "FINISH"),
                    ("cancel", "CANCEL"),
                ],
                default="open",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256)),
                ("image", models.ImageField(upload_to="static/item/")),
                (
                    "height",
                    models.FloatField(blank=True, default=0, verbose_name="Height"),
                ),
                (
                    "width",
                    models.FloatField(blank=True, default=0, verbose_name="Width"),
                ),
                (
                    "length",
                    models.FloatField(blank=True, default=0, verbose_name="Length"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("in_progress", "IN_PROGRESS"),
                            ("resolve", "RESOLVE"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, verbose_name="Start")),
                ("end_time", models.DateTimeField(blank=True, verbose_name="End")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embroidery.order",
                    ),
                ),
            ],
        ),
    ]
