# Generated by Django 3.2.15 on 2022-10-03 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embroidery", "0006_auto_20221003_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="output_format",
            field=models.CharField(
                choices=[
                    ("JPEG", "JPEG"),
                    ("JPG", "JPG"),
                    ("PNG", "PNG"),
                    ("PDF", "PDF"),
                    ("DST", "DST"),
                    ("EMB", "EMB"),
                    ("PES", "PES"),
                    ("CND", "CND"),
                    ("EXP", "EXP"),
                    ("VP3", "VP3"),
                    ("JEF", "JEF"),
                    ("HUS", "HUS"),
                    ("ART", "ART"),
                ],
                default="PDF",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="end_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, verbose_name="End"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="start_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, verbose_name="Start"
            ),
        ),
    ]
