# Generated by Django 3.2.15 on 2022-11-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0007_auto_20221119_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer 1668842178', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order 1668842178', max_length=256),
        ),
    ]
