# Generated by Django 3.2.15 on 2022-10-03 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("embroidery", "0007_auto_20221003_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("in_progress", "IN_PROGRESS"),
                    ("pending", "PEDNING"),
                    ("resolve", "RESOLVE"),
                    ("cancel", "CANCEL"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
