# Generated by Django 3.2.15 on 2022-10-07 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0011_auto_20221007_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='embroidery.invoice')),
            ],
            options={
                'verbose_name_plural': 'InvoiceItem',
            },
        ),
    ]
