# Generated by Django 4.1.3 on 2022-11-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0011_alter_customer_name_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer 1669614310', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order 1669614310', max_length=256),
        ),
    ]
