# Generated by Django 4.1.3 on 2022-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0012_customer_password_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer 1669617188', max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order 1669617188', max_length=256),
        ),
    ]
