# Generated by Django 3.2.15 on 2022-10-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0014_remove_invoiceitem_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
