# Generated by Django 3.2.15 on 2022-10-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0015_remove_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, to='embroidery.item'),
            preserve_default=False,
        ),
    ]
