# Generated by Django 3.2.15 on 2022-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0020_auto_20221007_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('init', 'INIT'), ('paid', 'PAID'), ('debt', 'DEBT')], default='init', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('in_progress', 'IN_PROGRESS'), ('pending', 'PEDNING'), ('resolve', 'RESOLVE'), ('cancel', 'CANCEL')], default='open', max_length=50),
        ),
    ]
