# Generated by Django 3.2.15 on 2022-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embroidery', '0021_auto_20221007_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Note'),
        ),
    ]
