# Generated by Django 3.2.15 on 2022-10-04 15:52

from django.db import migrations, models
import modules.django_mailbox.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='document',
            field=models.FileField(upload_to=modules.django_mailbox.utils.get_attachment_save_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
